### ISSUE TITLE
if string contains % tr function crashes

### ISSUE THREAD

**Issue by Igor-Palaguta** [AliSoftware/SwiftGen#70] opened 2015-12-07 21:35 UTC
I have similar string ".. 5% ...". Function tr crashes as it always try to push this string to format, I think we should check number of arguments in tr before applying format
```
  private static func tr(key: String, _ args: CVarArgType...) -> String {
    let localizedString = NSLocalizedString(key, comment: "")
    if args.isEmpty {
      return localizedString
    }
    return String(format: localizedString, arguments: args)
  }
```

**Comment by AliSoftware** [comment] 2015-12-07 21:40
Can you be more specific with your example?

Such a use case should never happen as the private `tr` function should only be called from inside the enum and the enum with associated values should always have the exact right number of arguments as they were generated by parsing the keys and values in Localizable.strings. Except if my string parsing misinterpreted that `

**Comment by Igor-Palaguta** [comment] 2015-12-07 21:45
I have following ling in localized strings
"MY_PERCENT_STRING" = "5% from total amount";

When I use it in usual code I use NSLocalizedString("MY_PERCENT_STRING", comment: "")
I don't use it in any printf like function, so I should escape it

**Comment by Igor-Palaguta** [comment] 2015-12-07 21:48
tr(.MY_PERCENT_STRING) crashes as it uses format function inside

**Comment by AliSoftware** [comment] 2015-12-07 21:58
Woops sorry I closed this by mistake while posting my last comment.

Ok I see the case now.

We should definitely improve the parsing of the string to detect if the `%` is indeed used as a formatter prefix or not. But even in your specific case, Your string is actually a totally valid formatting placeholder. 

`% f` is actually totally valid per the printf-style formats, and means that it should expect a floating-point value as parameter (`%f`) but using a space as a padding character. And indeed you can try it: 

```
$ swift
Welcome to Apple Swift version 2.1 (700.1.101.6 700.1.76). Type :help for assistance.
  1> import Foundation
  2> String(format: "5% from total amount", 4.2) 
$R0: String = "5 4.200000rom total amount"
```

So with your string there is no way for SwiftGen to know if that "5% from" is expected to be a string literal or a string with a format placeholder `% f` which expects a float as argument, so it will generate an enum with an associated `Float` value.

**Comment by AliSoftware** [comment] 2015-12-07 22:05
Note that your fix might be able to prevent that crash if there is no argument given but I'd rather say that:

1. This is strange that the `case MY_PERCENT_STRING` entry in the enum wasn't generated with an associated value of type `Float` as it should have parsed the `% f` in your string as a float parameter, so that's probably a bug in the parser
2. Your fix won't work if there are actual parameters, like `"5% from total amount of %f euros"` where you'll need to pass the total amount as parameters anyway…

So not sure how we could resolve this in a consistent manner other than expecting you to escape that `%` character. But anyhow, there still seems to be an issue in the function parsing the `%` arguments in the strings (I knew it wasn't perfect!) as it should have then detected it as a string expecting a `Float` and add that associated value — and I'm not even sure the parser currently takes any escaped `%%` into account, I'd have to check that too.

_(I know that's not what you want to hear, as it means that the issue is not actually the crash itself, but the fact that it should have generated an associated value to that enum and that the fix would require you to use `5%% from …` anyway as there won't be any way for SwiftGen to know that this `% f` is not a formatting argument otherwise)_

**Comment by Igor-Palaguta** [comment] 2015-12-07 22:10
Sorry "5% f" - is example string, and % f is just luck
Really it was like this "2.9% + 30"

**Comment by AliSoftware** [comment] 2015-12-07 22:17
Ok doesn't change the fact that the [code parsing the string specifiers here](https://github.com/AliSoftware/SwiftGen/blob/master/GenumKit/Parsers/StringsFileParser.swift#L110-L153) needs improving indeed.

Would welcome any suggestion about how to improve that parsing while still handling the vastness of all the formatting possibilities, even stuff like `% 2.4f` and `% f` but detecting that `% +` is not valid anyway.

**Comment by AliSoftware** [comment] 2015-12-07 22:21
Note that even if you don't feel like fixing the parsing yourself / implementing the fix, I'd welcome any Unit Tests to cover as much use cases as possible (including cases like `2.9% + 30`, `5% from total`, `2.9% 3f` and `5%% of %.3f.`) so whoever implements the fix can ensure it both fix your case _but_ doesn't break already working use cases.

**Comment by Igor-Palaguta** [comment] 2015-12-07 22:24
tr should not pass such strings to String(format:, args:) function
% must be escaped just in case if string is used inside format, like: "%%5 among %d", but if it is used as is, as plain text escaping is not required. For fixing my case I added check to ```tr(key: String, _ args: CVarArgType...)``` as described before. I don't think isEmpty check break anything

**Comment by AliSoftware** [comment] 2015-12-07 22:26
Ah good point. So indeed your test might be a good security to avoid invoking formatting there — sorry for the misunderstanding :wink:

**Comment by Igor-Palaguta** [comment] 2015-12-08 16:00
I am not sure this fix can be applied, as somebody could already workaround this issue by escaping %
As a solution I see this: we apply this fix, and we display warning if user uses %% inside string, that does not have any argument
e.g.
"%%5 in %d" - correct string
"%5 in 100" - correct string
"%%5 in 100" - warning

**Comment by AliSoftware** [comment] 2015-12-08 21:13
I'm not sure I agree with (1) as someone could willingly want the `%%` as a string literal for whatever reason, it's not up to SwiftGen to impose that `%%` is not a valid literal either.

But your solution of detecting if args is empty then don't use `String(format:)` should work, shouldn't it? Why do you say that "you're not sure your fix can be applied"?

**Comment by AliSoftware** [comment] 2016-05-30 06:26
Any news on this feature? You seem to be the only one having this issue, which I'm not sure is really fixable other than using `%%` in your strings, so I'm considering closing this issue?

**Comment by AliSoftware** [comment] 2016-06-01 22:20
Closing both because lack of response and also because I'm still not convinced there is an easy solution to your specific use case.

If your `Localizable.strings` contains `"MY_PERCENT_STRING" = "5% from total amount";` then SwiftGen will generate `case MY_PERCENT_STRING(Float)` (misreading `% f` here for a placeholder), not `case MY_PERCENT_STRING`. So I can't see how it might be _crashing_?

I'd understand that it doesn't generate the `case` you _expect_, as you would want that `case` not to have associated value because you consider that `% f` not to be a format placeholder, but that wouldn't cause a crash, and anyway there is no way for SwiftGen to know when you use a totally valid printf-like placeholder like `% f` in your string that you don't mean it to be a placeholder… so you'd have to escape it in your `Localizable.strings` file.

**Closed by AliSoftware** 2016-06-01 22:20 UTC
Labels: difficulty: easy, status: wont fix
